engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
  pep8:
    enabled: true
  radon:
    enabled: true
  sonar-python:
    enabled: true
    config:
      tests_patterns:
      - tests/**

ratings:
  paths:
  - "**.py"
